name: rpmlauncher
description: A multi-functional Minecraft Launcher power by The RPMTW Team,Made with Flutter and Dart.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+beta

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  http:
  url_launcher:
  path_provider: ^2.0.1
  split_view:
  path:
  file_selector_platform_interface: ^2.0.0
  file_selector_linux:
  file_selector_macos:
  file_selector_windows:
  file_selector:
  archive: ^3.1.2
  crypto:
  system_info: ^1.0.1
  oauth2: ^2.0.0
  dart_minecraft:
  dynamic_themes:
  intl: ^0.17.0
  auto_size_text: 3.0.0-nullsafety.0
  toml: ^0.11.0
  line_icons: ^2.0.1
  flutter_markdown: ^0.6.6
  dio_http: ^5.0.4
  no_context_navigation: ^2.1.2
  flag: ^5.0.1
  args: ^2.3.0
  contextmenu: ^2.0.1
  provider: ^6.0.1
  connectivity_plus: ^1.2.0
  pub_semver: ^2.1.0
  desktop_window: ^0.4.0
  dart_big5: ^0.0.5
  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size
      ref: 03d957e8b5c99fc83cd4a781031b154ab3de8753
  rpmlauncher_plugin:
    path: plugin
  io: ^1.0.3
  watcher: ^1.0.1
  xml: ^5.3.1
  smooth_page_indicator: ^1.0.0+2
  quiver: ^3.0.1+1
  dart_discord_rpc:
    git: https://github.com/RPMTW/dart_discord_rpc.git
dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
  msix: ^2.6.2

flutter:
  uses-material-design: true

  assets:
    - images/Minecraft.png
    - images/Forge.jpg
    - images/Fabric.png
    - images/CurseForge.png
    - images/Modrinth.png
    - images/FTB.png
    - images/Logo.png
    - lang/en_us.json
    - lang/zh_tw.json
    - lang/zh_hk.json
    - lang/zh_cn.json
    - lang/ja_jp.json
  fonts:
    - family: font
      fonts:
        - asset: fonts/NotoSansCJKtc-Regular.otf #Source: https://fonts.google.com/noto
    - family: mono
      fonts:
        - asset: fonts/NotoSansMono-Medium.ttf #Source: https://fonts.google.com/noto

msix_config:
  display_name: RPMLauncher
  publisher_display_name: The RPMTW Team
  publisher: E=rpmtw666@gmail.com, CN=ga.rpmtw.rpmlauncher, OU=The RPMTW Team, O=The RPMTW Team, L=TW, S=TW, C=TW
  identity_name: ga.rpmtw.rpmlauncher
  logo_path: ./images/Logo.png
  start_menu_icon_path: ./images/Logo.png
  tile_icon_path: ./images/Logo.png
  icons_background_color: "#000000"
  architecture: x64
  capabilities: "internetClient,allowElevation,internetClientServer,sharedUserCertificates"
  certificate_path: ./windows/MsixInstaller/CERTIFICATE.pfx
  certificate_password: "rpmtw"
  languages: "zh-tw, zh-cn, zh-hk, en-us, ja-jp"
