name: UpdateJson
description: test

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  args: ^2.2.0
  http: ^0.13.3

dev_dependencies:
  flutter_lints: ^1.0.4
