name: Pull Request Analyze
on: [pull_request]

jobs:
  Analyze:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@main
        with:
          flutter-version: 3.3.9
          cache: true
      - run: flutter pub get
      - name: Analyze code
        uses: zgosalvez/github-actions-analyze-dart@524d7c3e24b8bd8feab6c5513871a6bc87b2d97b

  Coverage:
    strategy:
      matrix:
        runs-on: [ubuntu-latest, windows-latest, macos-latest]
      fail-fast: false
    runs-on: ${{ matrix.runs-on }}
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@main
        with:
          flutter-version: 3.3.9
          cache: true
      - name: Generate coverage
        run: |
          flutter pub get
          flutter test --coverage
        shell: bash
        continue-on-error: true
      - name: Upload to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage/lcov.info

  Test-Build:
    strategy:
      matrix:
        runs-on: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - runs-on: ubuntu-latest
            output-path: build/linux/x64/release/bundle
            os-name: linux
          - runs-on: windows-latest
            output-path: build/windows/runner/Release
            os-name: windows
          - runs-on: macos-latest
            output-path: build/macos/Build/Products/Release/rpmlauncher.app
            os-name: macos
      fail-fast: false
    runs-on: ${{ matrix.runs-on }}
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@main
        with:
          flutter-version: 3.3.9
          cache: true
      - name: Install Dependencies
        if: ${{ runner.os == 'Linux' }}
        run: |
          sudo apt-get update
          sudo apt-get install ninja-build libgtk-3-dev libblkid-dev
      - name: Build for ${{ runner.os }}
        run: |
          flutter config --enable-${{ matrix.os-name }}-desktop
          flutter build ${{ matrix.os-name }} --dart-define="build_id=${{ github.run_number }}" --dart-define="version_type=debug" --dart-define="version=${{ secrets.VERSION  }}"
      - name: Upload File
        uses: actions/upload-artifact@v2
        with:
          name: RPMLauncher-${{ runner.os }}-debug
          path: ${{ matrix.output-path}}
